#ifndef _LANG_HPP_
#define _LANG_HPP_
#include "cJSON.h"

enum{
STRING_RETROGAME=0,
STRING_FAVORITE,
STRING_GAME,
STRING_ARCADE,
STRING_NEOGEO,
STRING_FC,
STRING_SFC,
STRING_GB,
STRING_GBA,
STRING_MD,
STRING_GPSP,
STRING_SMS,
STRING_PS,
STRING_PCE,
STRING_OTHER,
STRING_SETTING,
STRING_GAME_INFO,
STRING_DEVICE_INFO,
STRING_PLAYLIST,
STRING_FILE,
STRING_ADC_INFO,
STRING_ENCDEC_TEST,

STRING_SETTING_KEYS_MAP,
STRING_SETTING_LANGUAGE,
STRING_SETTING_VOLUME,
STRING_SETTING_BGM_VOLUME,
STRING_SETTING_BRIGHTNESS,
STRING_SETTING_REFRESH_ROMS,
STRING_SETTING_FACTORY_RESET,
STRING_SETTING_FLASH_MODE,
STRING_SETTING_DEVICE_INFO,
STRING_SETTING_HARDWARE_TEST,
STRING_SETTING_ADC_INFO,
STRING_SETTING_STATUS_COLON,
STRING_SETTING_DELAY_COLON,
STRING_SETTING_OK_RATE_COLON,
STRING_SETTING_FAIL_RATE_COLON,
STRING_SETTING_STOPPED,
STRING_SETTING_RUNNING,
STRING_SETTING_ADC_COLON,
STRING_SETTING_CHARGING,
STRING_SETTING_OTG,
STRING_SETTING_DISCONNECTED,
STRING_SETTING_ERROR,

STRING_FAVORITE_SMALL,
STRING_CANCEL,
STRING_OK,
STRING_SECONDS,
STRING_IN,
STRING_PLAY_LIST,
STRING_CLEAR,
STRING_OPEN_SMALL,
STRING_REMOVE,
STRING_REFRESH,
STRING_REFRESH_ROMS,
STRING_ADD_FAVORITE,
STRING_UPDATE,
STRING_UPDATE_PROMPT,
STRING_SPACE_LOW_FORMAT,

STRING_SETTING_MODE,
STRING_SETTING_SERIAL,
STRING_SETTING_VERSION,
STRING_SETTING_CPU,
STRING_SETTING_MHZ_FORMAT,
STRING_SETTING_MEMORY,
STRING_SETTING_MEGA_PROMPT,
STRING_SETTING_SD_CARD,

STRING_RESUME_DEFAULT_SETTING,
STRING_RESUME_DEFAULT_SETTING_PROMPT,
STRING_REFRESH_ROMS_PROMPT,
STRING_RESET,

STRING_KEYMAP_DEFAULT,
STRING_KEYMAP_MODE1,
STRING_KEYMAP_MODE2,
STRING_UNKNOWN,

STRING_LOADING,
STRING_LOADING_SMALL,

STRING_CLEAR_LIST,
STRING_CLEAR_LIST_PROMPT,
STRING_CLEAR_FAVORITE,
STRING_CLEAR_FAVORITE_PROMPT,
STRING_REMOVE_FAVORITE,
STRING_REMOVE_FAVORITE_PROMPT,
STRING_SCAN_GAMES,
STRING_GAMEINFO,
STRING_CREATE_CACHE,
STRING_POWER_OFF,
STRING_POWER_OFF_STR_FORMAT,

STRING_OPEN,
STRING_BACK,
STRING_NAV,
STRING_MENU,

STRING_CONTINUE,
STRING_SAVE,
STRING_LOAD,
STRING_VOLUME,
STRING_EXIT_GAME,
STRING_RECORD_FORMAT,
STRING_EMPTY,
STRING_NOTHUMB,
STRING_LOAD_FAIL_SMALL,
STRING_SAVE_FAIL_SMALL,
STRING_SAVE_OK_FORMAT,
STRING_FULLSCREEN,
STRING_ON,
STRING_OFF,
STRING_MAX,
};

extern const char * gDefaultStrs[STRING_MAX];

#ifndef X86
#define LANG_PATH "/customer/app/lang"
#else
#define LANG_PATH "./lang"
#endif



cJSON * initShortLangJSON(const char * desc);
void uninitShortLangJSON(cJSON * json);
const char * getLangInJSON(cJSON *json, int index);

#endif